Repository r0b-adams/portfolio, pull requests merged in 2022-06, with the labels that each got.

#49 added mockups
  public/images/console-log-mockup.png
  public/images/dad-jokes-mockup.png
  public/images/pantrimonium-mockup.png
  public/images/traductora-mockup.png
  public/images/vedomý-mockup.png
Labels: enhancement

#51 added link to resume, updated summary
  pages/About.tsx
Labels: enhancement

#52 Mobile disable active pg link
  components/Nav.tsx
  components/NavOverlay.tsx
Labels: bug

#54 added ternary to disable pointer until animation
  pages/index.tsx
Labels: bug

#55 added scroll to top btn
  components/Layout.tsx
  public/icons/upIcon.svg
Labels: enhancement

#60 Animate resume link
  pages/about.tsx
Labels: enhancement, animation

#64 added priority flag to image components
  components/Project.tsx
  pages/projects/[id].tsx
Labels: enhancement

#76 Colors
  components/Footer.tsx
  components/HeaderBorder.tsx
  components/Layout.tsx
  components/Logo.tsx
  components/NavList.tsx
  components/NavOverlay.tsx
  components/NewtonsCradle.tsx
  pages/about.tsx
  pages/index.tsx
  public/icons/upIcon.svg
  tailwind.config.js
Labels: enhancement
